### ISSUE TITLE
Download path inconsistency between post-install and defaults.

### ISSUE THREAD

**Issue by akateiva** [nodkz/mongodb-memory-server#101]
Currently, the post-install script downloads the binaries to `/node_modules/mongodb-memory-server/node_modules/.cache/mongodb-memory-server/mongodb-binaries/latest/mongod`, which I believe is due to the cwd being set to /node_modules/mongodb-memory-server when post-install is run. At runtime, the binaries are downloaded anew to `/node_modules/.cache/mongodb-memory-server/mongodb-binaries`. Perhaps the easiest fix for this would be checking both directories in MongoBinary.js ?

To reproduce:
```
docker run -it --rm node:11 /bin/bash
root@444a1d59d65f:/# npm init --yes
Wrote to /package.json:

{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


root@444a1d59d65f:/# npm install --save-dev mongodb-memory-server

> mongodb-memory-server@2.7.0 postinstall /node_modules/mongodb-memory-server
> node ./postinstall.js

mongodb-memory-server: checking MongoDB binaries cache...
mongodb-memory-server: binary path is /node_modules/mongodb-memory-server/node_modules/.cache/mongodb-memory-server/mongodb-binaries/latest/mongod
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN mongodb-memory-server@2.7.0 requires a peer of mongodb@>= 3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @1.0.0 No description
npm WARN @1.0.0 No repository field.

+ mongodb-memory-server@2.7.0
added 81 packages from 48 contributors and audited 166 packages in 35.706s
found 0 vulnerabilities

root@444a1d59d65f:/# node
> const path = require('path');
undefined
> const findCacheDir = require('find-cache-dir');
undefined
> path.resolve(findCacheDir({ name: 'mongodb-memory-server' }), 'mongodb-binaries');
'/node_modules/.cache/mongodb-memory-server/mongodb-binaries'
```

**Comment by AJRdev** [comment]
@akateiva The binaries are downloaded in the same directory in the post_install script and at runtime, both of them in the directory **/node_modules/.cache/mongodb-memory-server/mongodb-binaries**, they both pass through the getPath method of the MongoBinary class.

When the download is done, a folder corresponding to the version of mongodb used is created in that directory, in your case that folder is **/latest/mongod** containing the binary.

So if you downloaded the binary in the post install script and you then use the module it should not download it again since the binary is already present in the right directory. 

In which context are you using the module ? In different CI jobs ? 
On your trace I cannot see the new download of the binary.

**Comment by akateiva** [comment]
@AJRdev I'm using the module for tests in a CI job.

In my trace I show the result of `path.resolve(findCacheDir({ name: 'mongodb-memory-server' }), 'mongodb-binaries');`, which is taken from [MongoBinary.js line 33](https://github.com/nodkz/mongodb-memory-server/blob/524181b4b45551f4e5f69b598e37b4e3a005c9ce/src/util/MongoBinary.js#L33) . You can see that the directory to which the binaries were downloaded during post-install to the .cache folder mongodb-memory-server package, while at run-time the binary path is downloaded to the root package's .cache folder.

Anyway, I added `const mongod = new mongoms.MongoMemoryServer({debug: true});` to the trace so you can see the download dir.
```
docker run -it --rm node:11 /bin/bash
root@3971eceabc15:/# npm init --yes
Wrote to /package.json:

{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


root@3971eceabc15:/# npm install --save mongodb mongodb-memory-server

> mongodb-memory-server@2.7.0 postinstall /node_modules/mongodb-memory-server
> node ./postinstall.js

mongodb-memory-server: checking MongoDB binaries cache...
mongodb-memory-server: binary path is /node_modules/mongodb-memory-server/node_modules/.cache/mongodb-memory-server/mongodb-binaries/latest/mongod
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @1.0.0 No description
npm WARN @1.0.0 No repository field.

+ mongodb-memory-server@2.7.0
+ mongodb@3.1.9
added 90 packages from 52 contributors and audited 177 packages in 33.606s
found 0 vulnerabilities

root@3971eceabc15:/# node
> const mongoms = require('mongodb-memory-server');
undefined
> const mongod = new mongoms.MongoMemoryServer({debug: true});
Autostarting MongoDB instance...
undefined
>   Mongo[33809] Starting MongoDB instance with following options: {"port":33809,"dbName":"25fe9f79-3061-43e0-931c-73e502341f3b","uri":"mongodb://127.0.0.1:33809/25fe9f79-3061-43e0-931c-73e502341f3b","storageEngine":"ephemeralForTest","dbPath":"/tmp/mongo-mem-42KwwXQYlN1Sfm"} +0ms
  Mongo[33809] MongoBinary options: {"downloadDir":"/node_modules/.cache/mongodb-memory-server/mongodb-binaries","platform":"linux","arch":"x64","version":"latest"} +7ms
  Mongo[33809] Downloading: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-latest.tgz +38ms
Downloading MongoDB latest: 53.7 % (44.7mb / 83.3mb)
(To exit, press ^C again or type .exit)
> Downloading MongoDB latest: 69 % (57.5mb / 83.3mb)
```

**Comment by AJRdev** [comment]
@akateiva Oh my bad, I misread the two paths..
Yes so there is a real problem that we didn't saw by running our CI jobs on the project where the _post_install_ script path and runtime path for the binary download were the same because the _post_install_ script is at the root level of the project.

In your case and for everyone installing this module, the _post_install_ script is at the root of the mongodb-memory-server npm package in the node_module directory not a the root of the project..

So this line : 
```javascript 
path.resolve(findCacheDir({ name: 'mongodb-memory-server' }), 'mongodb-binaries'))
```
is searching for the binary in the node_modules directory of the npm package (**/node_modules/mongodb-memory-server/node_modules/.cache/mongodb-memory-server/**) in the _post_install_ script and in the node_module and not at the root of the project like at runtime (**/node_modules/.cache/mongodb-memory-server/**).

The is quite an issue, because I can't see how we could detect in the _post_install_ script that we should download the binary in the node_modules of the project and not the node_modules of the package itself, we didn't had this problem before because the default path was : 
```javascript
path.resolve(os.homedir(), '.mongodb-binaries');
```

@nodkz Any thoughts on this ?

**Comment by nodkz** [comment]
Need to fix somehow. 😈

@guillaumervls have you bandwidth for taking care about this problem?

Related: https://github.com/nodkz/mongodb-memory-server/pull/99

**Comment by guillaumervls** [comment]
Nice catch ! Here is a fix https://github.com/nodkz/mongodb-memory-server/pull/106 using the [`cwd` option](https://github.com/avajs/find-cache-dir#cwd)

**Comment by AJRdev** [comment]
@guillaumervls Nice fix ;)
