### ISSUE TITLE
Doesn't Mongo have in-memory engine?

### ISSUE THREAD

**Issue by i0natan** [nodkz/mongodb-memory-server#104]
Thanks for the good work guys.

Asking for learning purposes -what is the added-value of this lib over Mongo built-in memory server?

**Comment by YuriGor** [comment]
This package uses mongo built-in memory server. 
It downloads, starts and stops mongoDB instance automatically without any actions required by user.
I found this package super useful for unit testing of my db-related code.
Instead of writing db mocks, I just use real DB, and all the tests will run on any machine where my soft will be installed, no pre-installed mongoDB will be required, no additional access configuration.
For example [look here](https://github.com/YuriGor/mongoose-slug-updater/tree/master/test)

**Comment by i0natan** [comment]
@YuriGor Sounds super-useful, thanks
