### ISSUE TITLE
integrate with mocha

### ISSUE THREAD

**Issue by nthanhhai2909** [nodkz/mongodb-memory-server#220]
I have integrated MongoDB-memory-server within mocha. Then I prepared DB on _before hook_. 
Then I have six cases for testing. The problem is when I run for each case it's okay, but when I run all test, something case went wrong!!!  These cases don't get data from DB.

**Comment by losikov** [comment]
I did an integration with mocha too. One of properties in the schema:
login: {type: String, required: true, lowercase: true, trim: true, index: true, unique: true}
I save objects with the same 'login' value. When I run a separate test file, it works; when all via 'npm test', it always fails - duplicates are created in db.

**Comment by AJRdev** [comment]
@nthanhhai2909 What kind of test are you doing ? Are you modifying the same set of data in each tests ?

@losikov Did you use the Mocha after or afterEach hook (https://mochajs.org/#hooks) to delete the set of data after each test suite ? 
Because it is normal that you will have duplicates in your database because the object are persistent in the temporary database if you d'ont clean between each of your test suites

**Comment by hasezoey** [comment]
Closing - because of no further information (as asked by @AJRdev)

if anyone should have "the same issue", please create a new issue
