### ISSUE TITLE
What MONGOMS_DOWNLOAD_MIRROR to use for Manjaro Linux

### ISSUE THREAD

**Issue by franz-see** [nodkz/mongodb-memory-server#419]
## Versions

- NodeJS: 10.16.1
- mongodb-memory-server-*: 6.6.7
- mongodb: 4.4.1
- mongoose: 5.10.10
- system: Manjaro Linux 20.2

```
$ node --experimental-repl-await
> const getos = require('getos')
> const { promisify } = require('util')
> let os = await promisify(getos)()
> console.log(os)
{ os: 'linux',
  dist: 'Manjaro Linux',
  codename: 'nibia',
  release: '20.2' }
```

package: mongo-memory-server-core

## What is your question?

I am on Manjaro Linux and I want to use mongo-memory-server. What `MONGOMS_DOWNLOAD_MIRROR` to use for Manjaro Linux?

**Comment by hasezoey** [comment]
you probably mean `MONGOMS_ARCHIVE_NAME` (added in 7.0)

(because there are not many mirrors of the binaries, and if there are, probably not with manjaro / arch)

from what i know, Manjaro is based off Arch, look into #302 

---

if you should find an binary that works on manjaro / arch, you can open an PR and add it to the code, or write it here for future use

**Comment by franz-see** [comment]
Thanks @hasezoey . Found a way to make it work. I set it to 4.1.6 and it works on Manjaro
