### ISSUE TITLE
Use 'legacy' package as fallback

### ISSUE THREAD

**Issue by wingedfox** [nodkz/mongodb-memory-server#43]
https://github.com/nodkz/mongodb-memory-server/blob/3fb53263d50d64bb61f621075d9b9420843fe412/src/util/MongoBinaryDownloadUrl.js#L85

it worth to simply return empty string to fall back to 'legacy' distribution instead of throwing an error.

**Comment by nodkz** [comment]
For what OS do you receive this error? Better to add explicitly your os and package name resolving for it.

For now we cannot remove this error cause need to decide which `rhel`, `ubuntu`, `debian` version should be used as legacy. Or I something missing and exists some magic package which works everywhere?

**Comment by wingedfox** [comment]
Gentoo does not match anything from above, but perfectly works with legacy package, it is even used by in official ebuild.

This one is legacy, just do not add any release-specific suffix:
```
https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.6.2.tgz
```

**Comment by nodkz** [comment]
Can you add PR? Out of office now, but can merge and publish new version from mobile.

**Comment by wingedfox** [comment]
Ok, I'll take a look.
Btw, why not to use https://github.com/nodkz/mongodb-memory-server and let it download everything?

**Comment by wingedfox** [comment]
Sorry, did not check message after posting, preview was ok :)
There was a link to `mongodb-prebuilt` on github.

**Comment by nodkz** [comment]
At the beginning, I used `mongodb-prebuilt` but with time I switched to own implementation due to following reasons:
- own global lock for avoiding multiple downloads with parallel tests
- `~/.mongodb-binaries` folder size decreased from 200MB to 20MB (it much more pleasant for caching on CI)
- expose more tunable options (i do not remember exactly what was added)
- completely refactor code (es6, async/await, flowtype static analysis)
