### ISSUE TITLE
This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.

### ISSUE THREAD

**Issue by sebastiangug** [nodkz/mongodb-memory-server#577]
We're currently on explicitly version 7.0.0 and whenever we try to use transactions with a replicaset we get: 

```        mongod = new MongoMemoryReplSet({
          replSet: {
            count: 3,
          },
        });
        await mongod.start();
        const mongoUri = mongod.getUri() + "?retryWrites=false";
```

Attempting to create a replicaset, everything works fine with the standard one but unfortunately even if we try to append that to the connection uri -- it will not work. 

Any ideas on what we need to do to make this work? currently blocking all our tests. 

Thank you!

**Comment by hasezoey** [comment]
next time, please use the issue template and dont remove it

---

from what i can tell, `retryWrites` requires the storage engine to not be `ephermeralForTest`, you can change it by using something like `new MongoMemoryReplSet({ replset: { storageEngine: 'wiredTiger' } })`

also, `retryWrites` is required for transaction support, so it may just happen that this error only comes when using transactions

see [Retryable Writes and Multi-Document Transactions¶](https://docs.mongodb.com/manual/core/retryable-writes/#retryable-writes-and-multi-document-transactions)

> `const mongoUri = mongod.getUri() + "?retryWrites=false";`

this is incorrect, if you are using a replset, then url encoded options are already added, so the correct thing would be `const mongoUri = mongod.getUri() + "&retryWrites=false";`, but i would recommend to set this option in the connection options of mongodb, not in the url

---

if you are really on `7.0.0`, then i would recommend to upgrade to the latest `7.x` version, otherwise if possible to upgrade to `8.x`
