### ISSUE TITLE
Test failing when i pass storageEngine: wiredTiger

### ISSUE THREAD

**Issue by aliaqat-pai** [nodkz/mongodb-memory-server#610]
## Versions

- NodeJS: 16.14.0
- mongodb-memory-server-*: 8.3.0
- mongodb: 5.0.3
- mongoose: 5.13.13
- system: MacOS M1 Max

package: mongo-memory-server

## What is your question?

I am using mongo-memory-server to setup it with mocha. When i run the test without storageEngine it works fine, but as soon as i give the `storageEngine: wiredTiger` i get following messages from mongoose:

```
{"level":"info","message":"Mongoose default connection open to mongodb://127.0.0.1:64859,127.0.0.1:64860,127.0.0.1:64861,127.0.0.1:64862/?replicaSet=testset"}
{"level":"info","message":"Mongoose default connection connected"}
CLEANING
{"level":"info","message":"Mongoose default connection disconnected"}
```
and test fails, i have same setup on windows machine which works fine.

Here is my opts which i am passing to mongoose while creating connection

```ts
const opts: ConnectOptions = {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useCreateIndex: true,
    keepAlive: true,
    serverSelectionTimeoutMS: 100000
  }
  
const getMongoInMemoryServerUri = async () => {
  const replSet: MongoMemoryReplSet = await MongoMemoryReplSet.create({
    replSet: { storageEngine: 'wiredTiger', count: 4  }
  });

  await replSet.waitUntilRunning();

  const mongoUri = replSet.getUri();

  return mongoUri;
}

let connStr: string = await getMongoInMemoryServerUri();
  
mongoose.connect(connStr, opts)
 ```
 
 Here is log file
[typescript.log](https://github.com/nodkz/mongodb-memory-server/files/8130685/typescript.log)

**Comment by aliaqat-pai** [comment]
@hasezoey , thanks for the response,

Regarding 
> mongoose.connect(connStr, opts)

This is in a function, its actually is like

> return mongoose.connect(connStr, opts)

I am returning a promise


For stopping the instance i am using mocha global hook `afterAll`

and doing

> await mongoose.disconnect();

**Comment by aliaqat-pai** [comment]
@hasezoey , I added 

> await sleep(5000);

after awaiting `start` function and then it working fine, but still a simple test is taking 8000ms to complete

**Comment by hasezoey** [comment]
> await sleep(5000);

this should not be necessary, i would not know how this would be required

>  but still a simple test is taking 8000ms to complete

spinning up multiple instances of a replset and waiting for all of them to be started and then apply a replset config and wait for a primary takes a while, that is also why it is recommended to not do a new (replset)instance for each test

> For stopping the instance i am using mocha global hook afterAll
> and doing

are you only calling `mongoose.disconnect` and not also `replset.stop`?

**Comment by aliaqat-pai** [comment]
>  that is also why it is recommended to not do a new (replset)instance for each test

I think i am not creating a new replset on each test, actually its expressjs app, it starts the server once and make the. connection to the db one time 

And in mocha global hook `beforeAll` which runs once i am doing

``ts
beforeAll(done: (...args: any[]) => void) {
    logger.info('Root hook beforeAll');
    mongoose.connection.on('connected', done);

 }
``
and same in `afterAll` hook
``ts
  async afterAll() {
    await mongoose.disconnect()
  },
``

not using `replset.stop`

**Comment by aliaqat-pai** [comment]
I wrote a more simpler test before the one which i pasted above

```ts
it('Get list of companies 1', async () => {

  const resp = await request.get('/api/v1/companies');

  const names = resp.body.docs.map((v: { name: any; }) => v.name);

  expect(resp.status).to.be.eq(200);
})
```

I didn't took much time but as soon as i add any write operation that is taking 2000ms+ time to complete
as in above example there were 3 write operations to DB that one is taking 8000ms+

**Comment by hasezoey** [comment]
> I think i am not creating a new replset on each test, actually its expressjs app, it starts the server once and make the. connection to the db one time

yes, i just mentioned it

> And in mocha global hook beforeAll which runs once i am doing
>     mongoose.connection.once('connected', done);

are you sure you want to listen on this instead of actually connecting in there (i dont know mocha well, is it maybe not able to be async?)


---

from what i can tell, the mongodb instances have problems communicating with each other and so fail to consistently elect a PRIMARY, which is required for write operations and instead of transitioning into SECONDARY, like in normal operation, instead because it cannot communicate with other instances it goes into RS_DOWN, which seems to stop all non-replset instance connections (like the nodejs connections)

this may be related to something like a firewall setting or something on apple's configuration, but i have no clue about that, sorry

thing you can maybe try:
- delete the mongodb binaries and try to let MMS redownload them (in your case the binaries are in `/Users/adilliaqat/.cache/mongodb-binaries`)
- try older versions of mongodb (like i have wrote earlier)
- try looking through network setting and / or firewall setting if there is anything related to that
- if there are rosetta (x86_64 to arm64 runner) settings, maybe look through there for something related to local networking
- try resetting your Apple Machine
