### ISSUE TITLE
Starting the instance failed... top: "instanceInfo" is not defined (never ran?) +0ms

### ISSUE THREAD

**Issue by romerodiesan** [nodkz/mongodb-memory-server#617]
## Versions

- NodeJS: 16.14.1
- mongodb-memory-server-*: 8.4.1 
- mongodb(the binary version): 4.4.6
- mongodb(the js package): 5>x
- mongoose: 6.2.7
- system: MacOS Monterey 12.3

package: mongo-memory-server

## What is your question?
I am trying to make some test (with jest and supertest) to an API with express and MongoDB (using mongoose). I make the following global setup:

```ts

import { MongoMemoryServer } from 'mongodb-memory-server';
import mongoose from 'mongoose';
// import { app } from '../app';
 
let mongo: any;
beforeAll(async () => {
  process.env.JWT_KEY = 'asdfasdf';
 
  mongo = await MongoMemoryServer.create();
  const mongoUri = mongo.getUri();
  await mongoose.connect(mongoUri);
});
 
beforeEach(async () => {
  const collections = await mongoose.connection.db.collections();
 
  for (const collection of collections) {
    await collection.deleteMany({});
  }
});
 
afterAll(async () => {
  await mongo.stop();
  await mongoose.disconnect();
});

```

As you can see, the idea is to keep the MongoDB connection flowing until the tests finish running. But I got this error:

> console.warn
> Starting the instance failed, enable debug for more information

So I activated the debugger and discovered that it is about this error:

> MongoMS:MongoMemoryServer Mongo[unknown]: stop: Called .stop() method +14ms
>  MongoMS:MongoMemoryServer Mongo[unknown]: stop: "instanceInfo" is not defined (never ran?) +0ms

Anyone has an idea of what this is happend?

**Comment by hasezoey** [comment]
thanks for providing the log, i have seen a (probably) unrelated issue in your log, which i have mentioned in #618 

---

from your log i can parse that your are running MacOS with ARM architecture, but just to confirm, you are explicitly trying to run MongoDB Version `4.4.6`, right?

also, the real problem here is that mongodb immediately exists with error `Unknown system error -86` (probably system could not execute binary), which may be related that the binary is for x86_64 and somehow cannot run on your arm machine, maybe try to delete the binary and try to let it re-download it and check if rosetta (the x86_64 to arm runtime) is working

in your case the mongodb binaries are stored at `/Users/diesanromero/.cache/mongodb-binaries/`, so maybe try to delete the folder or all the content within

**Comment by romerodiesan** [comment]
@romerodiesan  Hi, thanks. That solved my error. I delete the folder in order to have a future clean download, and install Rosseta 2.
