### ISSUE TITLE
Jest Guide still not working

### ISSUE THREAD

**Issue by jimmythecode** [nodkz/mongodb-memory-server#658]
Sorry to raise this again. My previous issue got closed but I still don't think the matter has been resolved. I've copied and pasted the code from the guide into a working server, but there are several errors:
https://github.com/jimmythecode/mongodbmemoryserver-guide/tree/mongodb-memory-server-guide

Even when I fix the first few linter errors, the tests fail to run. There is nothing wrong with the server/app generally. I've got jest working successfully and I've even made a successful test with `mongodb-memory-server` / `mongoose` (using this example from stack: https://github.com/jimmythecode/mongodbmemoryserver-guide/tree/mongodb-memory-server-guide). It just seems that it would be worthwhile to get the guide code usable for novices like me.

**Comment by jimmythecode** [comment]
I've got it working with the following changes:
https://github.com/jimmythecode/mongodbmemoryserver-guide/commit/5a84af43fc225c092dd35ee2a1684dc14df041f2

**Comment by hasezoey** [comment]
from what i can tell (aside from the missing key in the config), there is no problem with the guide, only the code in your custom `utils/connect` is problematic:
- it creates a new instance when the file is loaded
- everytime `connect` is called a new instance is created and started, instead of using the one from `globalSetup`
- `connect` does not actually connect to anything

also `globalSetup.ts` import of `mongoose` in your project did not work because `esModuleInterop` is used, which requires sometimes different imports than without the option

PS: next time you think a issue not actually solved, please reopen (if possible and not too old) and update the problem in that issue instead of opening a new issue

**Comment by jimmythecode** [comment]
Thanks for the help! I wanted to reopen the previously closed thread but I couldn't find an option anywhere. I'll have a look again next time. Thanks again!

**Comment by hasezoey** [comment]
> I wanted to reopen the previously closed thread but I couldn't find an option anywhere. I'll have a look again next time.

if i remember correctly, in github if the author of the issue did not close it, it can only be re-opened by members, but this does not mean you cannot comment / ask to re-open it

**Comment by jimmythecode** [comment]
I couldn't find the original post to reply to. That was my first thought
too. I'll bear it in mind in case I just need to look harder next time.
Thanks

**Comment by hasezoey** [comment]
@jimmythecode is the issue solved or are there still open questions?

**Comment by jimmythecode** [comment]
Yes, it is working. Thanks for all of your help ☺
