### ISSUE TITLE
Is it possible to pass the URI as an argument when creating an instance?

### ISSUE THREAD

**Issue by felixjb** [nodkz/mongodb-memory-server#665]
## Versions

- NodeJS: 16.15.0
- mongodb-memory-server-*: 8.5.2
- mongodb(the js package): 4.5.0
- system: Ubuntu 20.04

package: mongo-memory-server 

## What is your question?

Is it possible to pass an URI as an argument when creating an instance of the database? This would help a lot when writing functional code. Currently I need to disable the ESLint when I attribute the URI to the process.env. I wish I could store a custom value in my .env file and then use this value to create my instance. That way I would not need to disable any linting rules.

**Comment by hasezoey** [comment]
> Is it possible to pass an URI as an argument when creating an instance of the database?

no it is not possible and it would also not make much sense.

though you can configure what port / ip it runs on

> I wish I could store a custom value in my .env file and then use this value to create my instance

i really recommend against this, but it is possible by statically defining a port

---

as a aside, which eslint option has to be disabled? for a example where MMS is used (also uses eslint), look at the typegoose [`globalSetup.ts`](https://github.com/typegoose/typegoose/blob/master/test/globalSetup.ts) file

**Comment by felixjb** [comment]
> though you can configure what port / ip it runs on

Is it possible to connect with the database knowing only the ip/port?

---

> as a aside, which eslint option has to be disabled? for a example where MMS is used (also uses eslint), look at the typegoose [globalSetup.ts](https://github.com/typegoose/typegoose/blob/master/test/globalSetup.ts) file

I'll take a look

**Comment by hasezoey** [comment]
> Is it possible to connect with the database knowing only the ip/port?

if it is not a replset, then yes, if it is you also need to know the replset name, see:

https://github.com/nodkz/mongodb-memory-server/blob/02452a44548c80386bc988fa5f406dfe8e3b049d/packages/mongodb-memory-server-core/src/util/utils.ts#L56-L65
https://github.com/nodkz/mongodb-memory-server/blob/02452a44548c80386bc988fa5f406dfe8e3b049d/packages/mongodb-memory-server-core/src/MongoMemoryServer.ts#L714
https://github.com/nodkz/mongodb-memory-server/blob/02452a44548c80386bc988fa5f406dfe8e3b049d/packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts#L334-L336

`getUri` is just basically a helper to automatically generate the full uri, because mongodb and mongoose only (from what i know) allow to use a full uri, not just ip+port+replsetname

**Comment by felixjb** [comment]
Thank you! It is clearer now for me. I guess I can go a different way then.

**Comment by hasezoey** [comment]
closing because question seems to be answered
