### ISSUE TITLE
Archive Combination does not exist `arm64-debian10-5.0.3`

### ISSUE THREAD

**Issue by k2xl** [nodkz/mongodb-memory-server#677]
## Versions

- NodeJS: 8.12.1
- mongodb-memory-server-*: 8.5.2 
- mongodb(the binary version): 0 
- mongodb(the js package): 0.0.0 
- mongoose: 6.2.4 
- system: M1 Macbook Pro

mongo-memory-server

## What is the Problem?

Host is Macbook Pro M1 (just installed Rosetta). Dockerfile is:
```
FROM node:18

ENV NEXT_TELEMETRY_DISABLED 1

WORKDIR /app

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

USER node

CMD ["npm","run", "dev"]
```

Error is:
```
Starting the MongoMemoryServer Instance failed, enable debug log for more information. Error:
Error: Status Code is 403 (MongoDB's 404)
This means that the requested version-platform combination doesn't exist
Used Url: "https://fastdl.mongodb.org/linux/mongodb-linux-arm64-debian10-5.0.3.tgz"
```

Running 
`cat /etc/os-release`
inside the container is:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

What's weird is that a colleague without an M1 does not see this error, which makes me think it is related to ARM vs Apple. Weird that MongoMemoryServer seems to be requesting for Debian10 even though the container Debian11. Any ideas of what to try and do?

`uname -a` for my colleague:
`Linux 62644ccaf4a7 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 GNU/Linux`

`uname -a` for me:
`Linux 7add78f0bd00 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 GNU/Linux`

In the mongodb-memory-server code it looks like it requests via:
`url.pathname = ${url.pathname}${this.platform}/${archive};`

His URL that is requested:
```
https://fastdl.mongodb.org/linux/mongodb-linux-arm64-debian10-5.0.3.tgz
```
I am downloading: http://downloads.mongodb.org/linux/mongodb-linux-x86_64-debian10-5.0.3.tgz

Looking at the list: https://www.mongodb.org/dl/linux there doesn't seem to be a debian but there is a ubuntu so we may try that

**Comment by hasezoey** [comment]
> Weird that MongoMemoryServer seems to be requesting for Debian10 even though the container Debian11. Any ideas of what to try and do?

it is not weird, MMS does some mapping on what archives can / will be used, like mongodb does sometimes not provide older binaries for newer distors, but those older binaries (of the older distro) will very likely still work on the newer distro

your case is just problematic because somehow it detects `arm64` inside the docker (which i didnt even know was possible, i though only x86_64 was supported in docker), so you may need to force x86_64 docker containers because no `arm64` (or `arm` in general) builds dont exist or `debian`

currently mongodb only provides `arm64` builds for ubuntu 16.04 (from what i can tell, there are still not arm64 / aarch64 builds of mongodb for macos), though there are many `aarch64` binaries (which are currently unused in MMS) for some linux distros

**Comment by hasezoey** [comment]
closing because there do not exist official binaries for debian + arm64(aarch64) and mapping to ubuntu is not really proper (but a workaround the user should manually do)
