### ISSUE TITLE
Can we use custom MongoDB variant like Percona Server for MongoDB?

### ISSUE THREAD

**Issue by yukha-dw** [nodkz/mongodb-memory-server#701]
## Versions

- NodeJS: 16.13.1
- mongodb-memory-server-*: 8.8.0
- mongodb(the binary version): 5.0.10
- mongodb(the js package): 4.7.0
- system: 

package: mongo-memory-server 

## What is your question?

Hello, i'm curious if we can use custom MongoDB variant like [Percona Server for MongoDB](https://docs.percona.com/percona-server-for-mongodb/5.0/index.html). It's based on vanilla MongoDB but have some exclusive feature like "ngram" language on Text Index. Thank you.

**Comment by hasezoey** [comment]
from what i can tell from percona, it *should* work, as long as you use a [system binary](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#system_binary), or find a actual archive url and it has the same structure and names as the official mongodb ones (unlikely, also could not find any download)

also output parsing may not be fully compatible if the output is changed (we read the output for errors and transitions to primary for replset)

**Comment by yukha-dw** [comment]
> from what i can tell from percona, it _should_ work, as long as you use a [system binary](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#system_binary), or find a actual archive url and it has the same structure and names as the official mongodb ones (unlikely, also could not find any download)
> 
> also output parsing may not be fully compatible if the output is changed (we read the output for errors and transitions to primary for replset)

Thanks @hasezoey, I have found this [download link](https://www.percona.com/downloads/percona-server-mongodb-LATEST/percona-server-mongodb-5.0.10-9/binary/) and might have similar structure with official mongodb. I'll try it later

**Comment by hasezoey** [comment]
> I have found this [download link](https://www.percona.com/downloads/percona-server-mongodb-LATEST/percona-server-mongodb-5.0.10-9/binary/) and might have similar structure with official mongodb

from what i can tell it has the same structure and names, but it also has a extra `lib` directory in it, i dont know if it will work without, because MMS only extracts the `mongod` binary

**Comment by sibelius** [comment]
can we reopen this related to 

https://github.com/typegoose/mongodb-memory-server/issues/742#issuecomment-2523452498

fully support percona could be a good thing

**Comment by sibelius** [comment]
try this https://github.com/sibelius/mongodb-memory-server-percona

**Comment by hasezoey** [comment]
> try this https://github.com/sibelius/mongodb-memory-server-percona

@sibelius That looks like a good project, though some notes:

(The following notes have been written against [`0.1.1`](https://github.com/sibelius/mongodb-memory-server-percona/tree/f4151edd2990d4a7da1bb4fcdefb6af13e6eb511))

> URL layout mismatch. MMS's downloader hard-codes fastdl.mongodb.org's flat path scheme and reads MongoDB's "Releases archive" page to enumerate versions. Percona's path is deeper (/downloads/percona-server-mongodb-8.0/percona-server-mongodb-8.0.20-8/binary/tarball/...) and there is no equivalent index.

I think there has been a misunderstanding, `mongodb-memory-server` never interacts with the archive page, i just requested it because it makes it a whole lot easier to see and debug the URL style across versions instead of just one or having to go through each one manually. (which is good to have as, at least with upstream mongodb, their url schemes changed across versions)
Additionally, `mongodb-memory-server` is hard-coded against `fastdl.mongodb.org` *only* for automatic download, you can still use the Config option [`DOWNLOAD_URL`](https://typegoose.github.io/mongodb-memory-server/docs/api/config-options#download_url) to completely overwrite the url, but you would loose the automatic version selection and this alone wouldnt be cross-platform.

> SYSTEM_BINARY is the official workaround, but MMS runs mongod --version on the binary on startup. On Ubuntu 24.04+ this fails: Percona links against libldap-2.5 (Ubuntu 24.04+ ships openldap 2.6, ABI-incompatible) and bundles libssl 3.0 (system libcurl wants 3.2 symbols). mongod exits without stdout and MMS used to crash on stdout.toString(). Fixed in 10.1.3-beta.1 with absolute-path normalization + a SYSTEM_BINARY_VERSION_CHECK=false escape hatch — but the underlying loader breakage was never fixed upstream.

This is kinda misleading as if even `mongodb --version` fails, normal startup would also fail. Maybe instead note that "Percona ships & requires more dependencies than normal mongodb (which it either ships with or requires manual installation), which `mongodb-memory-server` does not extract".

---

As there has been some time since i last looked, i searched through percona again to see if it is now easier to parse through the downloads. There still is no easy archive page or file indexes for the download, though there is the version selector.
I also took a look at their archive structure again, they dont seem to ship any libraries (archive path `lib/`) anymore, so extraction *should* just work. (for context, i took a look at `percona-server-mongodb-8.0.20-8-x86_64.noble-minimal` and `percona-server-mongodb-8.0.20-8-x86_64.noble`)
I also tried running them, but they still seem to require extra (system) libraries, which i would like mongodb-memory-server to avoid handling.

Finally, `mongodb-memory-server-percona` reads to me as if it is a complete replacement of `mongodb-memory-server`, though from what i can tell, it only replaces the download part, but still uses `mongodb-memory-server-core` for the actual runtime handling.

---

As for the implementation, as it is a extension of `mongodb-memory-server`, might i recommend to use `DryMongoBinary::generatePaths` and `DryMongoBinary::generateDownloadPath` over custom paths to have consistent binary paths? (you can still use sub-directories for percona, but the general path should likely be the same)

**Comment by sibelius** [comment]
Thanks for the feedback, if you want to bring this package to this monorepo, it is good for me

And also apply the modifications that you mentioned, it is also fine

This was the first time I made percona in memory engine work
