### ISSUE TITLE
memory db request result added a "_id":  with each time different value

### ISSUE THREAD

**Issue by chengtangzheng2021** [nodkz/mongodb-memory-server#709]
## Versions

- NodeJS: 0.0.0
- mongodb-memory-server-*: 0.0.0 
- mongodb(the binary version): 0.0.0
- mongodb(the js package): 0.0.0
- mongoose: 0.0.0 
- system: 

package: mongo-memory-server 

## What is your question?

This is a section in the middle of memory db query result:
```json
            "attributes": {
              "_id": "63547b375944ad67585e37e6",
              "buId": "909",
              "familyId": "13825",
```

This is the same secton in the result from real app db
```json
            "attributes": {
              "buId": "909",
              "familyId": "13825",
```

This data is composed into a request to call a remote service,
and in unit test the remotce service is mocked with nock, the nock is configure to check the request for matching, this added "_id":  with dynamic value make the mock can not match.
also noticed  "__v": 0, is added some where in the query reqult, but that is with a not changing value per request, so can made not to break the remote service call's mock matching. 
Is there a way there to handle this added dynamic value "_id":?

**Comment by chengtangzheng2021** [comment]
got this issue fixed

**Comment by hasezoey** [comment]
This Question was reopened, but i dont quite understand what the problem is, are you asking how to check a consistent result in a test for `ObjectId`?

**Comment by chengtangzheng2021** [comment]
"_id": "63547b375944ad67585e37e6" got added into inside an element that has inside it some elements, and "__v": 0 is added somewhere,
that is these two kind elements was added to the reponse doc that it doesn't have them inside Mongo.
querying momery mongo db with mongoose has this issue, querying with Mongodb client directly doesn't have this issue

**Comment by hasezoey** [comment]
i still dont understand your issue completely, so here is some general information:
- property `__v` is a mongoose property used for versioning (revision), see [Schema Options: `versionKey`](https://mongoosejs.com/docs/guide.html#versionKey)
- property `__t` is a mongoose property used for discriminators (and only added when using discriminators), see [Schema Options: `discriminatorKey`](https://mongoosejs.com/docs/guide.html#discriminatorKey)
- property `_id` is always set by mongodb, because it is the identifier for a document and cannot be disabled
- property `id` is a virtual in mongoose which takes any `_id` and in a [`get`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) transforms it to a string, i dont know if [`set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set) is supported

if you want to test documents to known states (like a `expect(doc).toEqual({ someobj: true })`, then you can safely ignore internal properties (like `__v`), but you will have to filter them out, as for `_id` you can on insert set them to something consistent, or also ignore it.
in case you use jest, you could also use matchers, see [a typegoose test example](https://github.com/typegoose/typegoose/blob/7e9f03f85966358676efd27b430b5cfac636838e/test/tests/biguser.test.ts#L64) and [jest documentation about expect](https://jestjs.io/docs/expect#expectanyconstructor)
