### ISSUE TITLE
Test suite fails to run in a testing workflow

### ISSUE THREAD

**Issue by AlexanderTheWise** [nodkz/mongodb-memory-server#760]
- NodeJS: 19.4.0
- mongodb-memory-server: 8.12.1
- mongodb(the binary version): 5.0.13
- mongodb(the js package): 5.1.0
- mongoose: 7.0.3
- system: Windows (local), Linux ubuntu-latest (testing workflow)

package: mongo-memory-server, mongo-memory-server-core

Two tests utilizing the mongodb memory server are passing locally, but only the first test passes during the testing action, while the second one fails. The second test utilizes mock-fs to simulate file uploading, and the error received is a 403 status code (MongoDB's 404). Despite trying a different version by specifying it as an argument while creating a new MongoMemoryServer instance, such as `'MongoMemoryServer.create({ binary: { version: 'X.Y.Z' } })'`, the issue persists. 

```
Status Code is 403 (MongoDB's 404)
    This means that the requested version-platform combination doesn't exist
      Used Url: "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-5.0.13.tgz"
    Try to use different version 'new MongoMemoryServer({ binary: { version: 'X.Y.Z' } })'
```

To my understanding, MongoDB utilizes the fs module to check binary presence, as stated in issue #251. Therefore, I strongly believe that there is an error between these two dependencies that is preventing the proper completion of the respective binaries download. I still do not understand why the tests are passing locally but not remotely, and specifically, why one test passes while the other does not.

**Comment by hasezoey** [comment]
> The second test utilizes mock-fs to simulate file uploading

MMS uses the filesystem to probe what distribution it is on and for downloading / checking for the binary.

guessing by that you are using `ubuntu-latest` (likely github actions?) and no `-ubuntuXXXX-` being present in the archive name, it failed to probe the distro (like `/etc/os-release`)

also i have just noticed that mongodb stopped shipping non-distro tagged versions since versions after 4.0, will need to update that one

>  I still do not understand why the tests are passing locally but not remotely, and specifically, why one test passes while the other does not.

i also cannot tell you why they are passing locally but not remotely, but guessing by that `mock-fs` affects MMS, you might be starting a instance in each test suite (or worse in every test), it is recommended to start one globally (like jest's `globalSetup` or through mocha's fixtures `mochaGlobalSetup`), see [Integration with Test Runners](https://nodkz.github.io/mongodb-memory-server/docs/guides/integration-examples/test-runners)
