### ISSUE TITLE
Unable to run mongodb memory server

### ISSUE THREAD

**Issue by AI0564-swati** [nodkz/mongodb-memory-server#783]
## Versions

- NodeJS: v18.17.0
- mongodb-memory-server-*: 8.13.0 
- mongodb(the binary version): 0.0.0
- mongodb(the js package): 0.0.0
- mongoose: ^6.8.2 
- system: Linux

package: mongo-memory-server 

## What is your question?

Whenever I run npm run test, I get the following error.

![issue](https://github.com/nodkz/mongodb-memory-server/assets/138203845/fa2b034f-568a-4aad-b88a-57f28b883235)

How do I resolve it?

**Comment by hasezoey** [comment]
yes, though the versions field is still not filled out, also next time please post it in code-blocks instead of a screenshot

your issue is that you dont have openssl 1.1.0 installed, i dont know your system (because the versions field is not filled out), so i assume you are running something latest like ubuntu 2204, which does not ship openssl 1.1.0 anymore, your options are:
- update the binary used by MMS via [Config Option `VERSION`](https://nodkz.github.io/mongodb-memory-server/docs/api/config-options#version) and see [Mongodb's archive](https://www.mongodb.com/download-center/community/releases/archive) for your distro and version you are using
- manually track down a package that provides openssl 1.1.0 and install it (not recommended)
- downgrade your distro to something that does ship openssl 1.1.0 (not recommended)
