### ISSUE TITLE
No export of  MongoMemoryServerOpts in package

### ISSUE THREAD

**Issue by nicholasfoden** [nodkz/mongodb-memory-server#795]
package: 
- mongo-memory-server
- mongo-memory-server-core

---

## What is your question?

Would it be possible to export `MongoMemoryServerOpts` and `MongoMemoryReplSetOpts` type in one of the packages?

Or is there a good reason why it is not exported?

### Use case

Writing a factory which spins up and seeds a database with test data

### Example proposed usage

```
function createTestDatabaseFactory(seed: SomeDataType, options: MongoMemoryServerOpts){
   const myinstance: MongoMemoryServer = MongoMemoryServer.create(options);
   // ... do some other things to seed the database
   return myinstance;
} 
```

Thanks for looking at this issue.

**Comment by hasezoey** [comment]
interface `MongoMemoryServerOpts` [is exported](https://github.com/nodkz/mongodb-memory-server/blob/f529e11c95431c8e66b95404a567c468ba689e75/packages/mongodb-memory-server-core/src/MongoMemoryServer.ts#L29C18-L29C39), [just not in the main entry-point](https://github.com/nodkz/mongodb-memory-server/blob/f529e11c95431c8e66b95404a567c468ba689e75/packages/mongodb-memory-server-core/src/index.ts), you will have to use direct import if you want to use it.

instead of `import { MongoMemoryServerOpts } from "mongodb-memory-server-core`
you have to `import { MongoMemoryServerOpts } from "mongodb-memory-server-core/lib/MongoMemoryServer`

or you could alternatively also use `Parameters<MongoMemoryServer['create']>[0]` instead of `MongoMemoryServerOpts` directly
