### ISSUE TITLE
Invalid version reported for version strings ending in -latest

### ISSUE THREAD

**Issue by DABH** [nodkz/mongodb-memory-server#841]
## Versions

- NodeJS: 16, 18, 20
- mongodb-memory-server-*: 9.1.3 
- mongodb(the binary version): 0.0.0 
- mongodb(the js package): 0.0.0 
- mongoose: 0.0.0 
- system: Ubuntu 22.04 LTS

package: mongo-memory-server(-core)

## What is the Problem?

My CI pipeline refers to MongoDB versions like "v6.0-latest".  This worked with `mongodb-memory-server(-core)` 8.x, but it seems like it no longer works in 9.x (9.1.3, at least).

## Code Example

Here's where we define the MongoDB version strings in our repo, for our CI pipeline: https://github.com/winstonjs/winston-mongodb/blob/master/.github/workflows/ci.yml

## Debug Output

Please see the GitHub Actions output here: https://github.com/winstonjs/winston-mongodb/pull/259

## Do you know *why* it happens?

*No*, but my guess is it may be something similar to https://github.com/nodkz/mongodb-memory-server/issues/734, where some code maybe slipped in between 8.x and 9.x that adds some semver comparison that doesn't sanitize for `-latest`?

Thanks so much for helping track this down, let me know if there's any other info you need from me!

**Comment by hasezoey** [comment]
thanks for reporting, issue is quite obvious: `v6.0-latest` is not a valid semver version and was not coerced to one beforehand, and since 9.0 there are checks against the version to decide the default storage-engine to use, because mongodb 7.0 removed the `ephermeralForTest`(in-memory) engine, which is faster than `wiredTiger` and so is still used as a default for lower versions
